# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

 

trigger:
- master

 

pool:
  vmImage: ubuntu-latest

 

steps:
- task: Maven@3

  inputs:
    mavenPomFile: 'Maven_test/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2

  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1

  inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'warfile'
        publishLocation: 'Container'
- task: CmdLine@2
  inputs:
    script: 'cd C:\agent\_work\r1\a\_Noha85.PipelineDemo\warfile\Maven_test\target  copy maven_test.war D:\Local\Testing\Udemy courses\Azure Devops Fundamentals for Testers -CICD+Project Boards\apache-tomcat-9.0.71-windows-x64\apache-tomcat-9.0.71\webapps'
